### ISSUE TITLE
Memory leak when running gogui-twogtp and CGOS

### ISSUE THREAD

**Issue by iopq** [ujh/iomrascalai#165]
On Windows, Iomrascalai takes more and more RAM as it keeps running, even across games.

**Comment by ujh** [comment]
Is this still happening with the latest nightly and our latest code? The problem is that I can't reproduce this on Mac OSX. When running the 9x9 and 13x13 benchmarks the memory usage (even after 200 games) never goes above 1GB.

**Comment by iopq** [comment]
Only Windows, I can't reproduce it on my Linux VM either.

**Comment by iopq** [comment]
Fixed by https://github.com/ujh/iomrascalai/pull/246
