### ISSUE TITLE
Continue searching when the result is unclear

### ISSUE THREAD

**Issue by ujh** [ujh/iomrascalai#209]
When the time for a move is up and the best move is selected it may be beneficial to continue searching a bit longer when the result isn't clear cut.

A possible strategy is as follows:

1. Select the best move by number of plays
1. Select the best move by win ratio
1. If the two aren't the same continue searching for N amount of time if there's still enough time left

See the computer go mailing list archive for inspiration or other solutions. Some bots seem to do this a lot and with M being the amount of time allocated initially for the move the go as far as 3*M for N.

**Comment by iopq** [comment]
I tried a similar approach (return the move with the best win ratio), but it didn't improve strength.

**Comment by ujh** [comment]
I'm not sure to be honest. I've currently trying a few things and none of them seem to improve the bot. Even the  large patterns (#298) isn't really working. I guess the time for easy wins is over.

**Comment by ujh** [comment]
Aaaaand it didn't help. 😁 It's probably better to just optimise the variables in `time_control` instead.
