### ISSUE TITLE
Use GnuGo level 10 in the 9x9 benchmark

### ISSUE THREAD

**Issue by ujh** [ujh/iomrascalai#239]
Now that we're beating GnuGo in almost 90% of cases using level 0 on 9x9 I think it would be a good idea to make it stronger by switching to level 10. This should be easy to do as only `bin/benchmark` needs to be enhanced a bit to change the level depending on the board size.

**Comment by iopq** [comment]
Why level 10? Why not level 12? Isn't that the strongest level?

**Comment by ujh** [comment]
Level 10 is what's used for the anchor on CGOS. So the advantage then is that it's easier to predict how we will be doing on CGOS. But if that's still not strong enough (I doubt it judging from the current results on CGOS) then we can of course switch level again.

**Comment by iopq** [comment]
Results are best when they're close to 50%, the higher the win percentage of one bot is the harder it is to make good predictions. I doubt GnuGo level 10 can beat us 50% at level 10.

**Comment by ujh** [comment]
That is true. So level 12 it is then.

**Comment by ujh** [comment]
Reading the source code of GnuGo suggests that you need to compile GnuGo with `./configure --enable-level=N` if you want levels higher than 10. Do you have any experience with that @iopq?

**Comment by iopq** [comment]
No idea, it doesn't complain if I set level 12, but I downloaded the binary. Maybe the binary is already compiled with that option?

**Comment by ujh** [comment]
I'll have to check more thoroughly some day. I just recompiled with level 20 to be on the safe side. ;)

**Comment by ujh** [comment]
When compiled with a different level it even behaves differently (thinking longer) when I specify the level. So I'll stick level 10 for now. That's what everyone uses anyway.
