### ISSUE TITLE
Use Rust Everywhere to get builds for all platforms automatically

### ISSUE THREAD

**Issue by iopq** [ujh/iomrascalai#260]
https://github.com/japaric/rust-everywhere
In particular, I put out fully statically linked Linux builds (the x86_64-unknown-linux-musl target) and it's annoying to get new versions of std every time we upgrade Rust

**Comment by ujh** [comment]
Very cool. I'll have a look at this!

**Comment by ujh** [comment]
We're now testing on OSX and on Linux with the x86_64-unknown-linux-musl target. Any other builds (besides Windows) we should add?

**Comment by ujh** [comment]
Uploading to the Github releases works as well: https://github.com/ujh/iomrascalai/releases/tag/0.3.2.pre2

**Comment by iopq** [comment]
for now that should be good

**Comment by ujh** [comment]
Thanks! I'll have a look at AppVeyor for the Windows builds as well in the next days.

**Comment by ujh** [comment]
The Windows build is done as well! https://github.com/ujh/iomrascalai/releases/tag/0.3.2.pre3
