### ISSUE TITLE
Have a flag for playing the game out to the end

### ISSUE THREAD

**Issue by iopq** [ujh/iomrascalai#312]
Maybe at first it would just be "not resigning", but it would be nice if we stopped passing when ahead if the game is not 100% over as well. This will be nice for generating "full games" between AI opponents instead of "a few moves and then resign" that happens on smaller boards.

**Comment by ujh** [comment]
That is true. The question is though if it even makes sense to use self-play here at all or if we produce cases of overfitting. Everybody seems to prefer playing against GnuGo as it's so different. I'll have to figure out which part (the self-play or the play on 19x19) produced the bad behaviour. And if we just play against GnuGo then we don't need this as GnuGo passes even earlier than we do. ;)

**Comment by iopq** [comment]
GnuGo has this switch, so we can enable it on both sides. I actually just want full games to see winning margins, so it's a totally separate purpose. It doesn't need to fill every move until there are only eyes, but it needs to fill all the dame points.

**Comment by ujh** [comment]
I just opened a PR for the "not resigning" part. And not passing when we're ahead can be achieved by switching the ruleset to Tromp/Taylor or CGOS (they are almost the same).

**Comment by iopq** [comment]
That seems a bit complicated (maybe rulesets should just be a combination of rules in  separate config files?). But good enough for now!

**Comment by iopq** [comment]
Wait, but what about when I don't want to play in Tromp/Taylor rules? There's superko considerations on smaller boards that actually prevented me from doing this.

**Comment by iopq** [comment]
Never mind, superko is separate. CGOS ruleset is what I want.

**Comment by ujh** [comment]
Yup, CGOS is almost Tromp/Taylor but not quite. But I'm not sure if it even makes sense to work with `master` right now. Before my changes we had a win percentage of ~ 40% against GnuGo on 13x13 and now we're at ~ 20%. I really need to fix this and then it might make sense to further investigate.
