### ISSUE TITLE
Feature Request/ Suggestion for a GUI

### ISSUE THREAD

**Issue by abhi18av** [ujh/iomrascalai#323]
Hello @ujh 

I just wanted to point out that for an excellent GUI perhaps you can work towards this [Electron based GUI](https://github.com/yishn/Sabaki). 

I see that you're working from a better backend point of view but, I hope that together these two can be a real treat :)

**Comment by ujh** [comment]
Very cool, I'll have to check that out some time. The engine supports GTP so it should be possible to use it out of the box. It won't be much fun as it's not very strong, but it is possible at least. ;)
