### ISSUE TITLE
Speed up Coord.neighbours()

### ISSUE THREAD

**Issue by ujh** [ujh/iomrascalai#66]
As of 176f41ddf155a8a266bf824d5c9592c8c426a300 most of the time seems to spent finding the neighbours of a `Coord`. A possible way to speed this up is to calculate the neighbours only once and keep them around for later uses.

Part of #53

**Comment by TisButMe** [comment]
This is also what my profiler told me was hot. It's called a ton by update_liberties() which re-computes a chain's liberties. I think a huge speed-up would come from being smarter about liberty updating.

**Comment by ujh** [comment]
Yes, *not* calling this method should save more time that speeding it up. :) Especially, as this is already incredibly fast anyway.
